install:
  - cmd: nuget restore Engine.sln
  - cmd: msbuild "Engine/Engine.vcxproj"
  
configuration: Debug

environment:
  GENERATOR: Visual Studio 15 2017
  PLATFORM: Win32
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
build: off